/**
 * Search test fixtures — representative dataset for comprehensive search verification.
 * Covers independent filters, combinations, edge cases, and pagination scenarios.
 */

import type { Property } from '../services/property.service.js';

// Base fixture properties with comprehensive attribute coverage
export const SEARCH_FIXTURES: Property[] = [
  {
    id: 'prop-001',
    owner_id: 'owner-1',
    title: 'Modern Apartment in Downtown',
    description: 'Beautiful modern apartment with stunning city views',
    price_per_night: 150,
    status: 'available',
    city: 'New York',
    country: 'USA',
    address: '123 Main St, New York, NY 10001',
    bedrooms: 2,
    bathrooms: 1.5,
    max_guests: 4,
    amenities: ['wifi', 'kitchen', 'ac', 'washing_machine'],
    property_type: 'Apartment',
    latitude: 40.7128,
    longitude: -74.006,
    average_rating: 4.8,
    review_count: 45,
    featured_until: null,
    created_at: '2024-01-15T10:00:00Z',
    slug: 'modern-apartment-downtown',
  },
  {
    id: 'prop-002',
    owner_id: 'owner-2',
    title: 'Cozy Studio in Brooklyn',
    description: 'Small studio near subway station',
    price_per_night: 85,
    status: 'available',
    city: 'Brooklyn',
    country: 'USA',
    address: '456 Oak Ave, Brooklyn, NY 11201',
    bedrooms: 1,
    bathrooms: 1,
    max_guests: 2,
    amenities: ['wifi', 'kitchen'],
    property_type: 'Studio',
    latitude: 40.6782,
    longitude: -73.9442,
    average_rating: 4.2,
    review_count: 12,
    featured_until: null,
    created_at: '2024-02-10T10:00:00Z',
    slug: 'cozy-studio-brooklyn',
  },
  {
    id: 'prop-003',
    owner_id: 'owner-3',
    title: 'Luxury Villa with Pool',
    description: 'Spacious villa with private pool and garden',
    price_per_night: 450,
    status: 'available',
    city: 'Los Angeles',
    country: 'USA',
    address: '789 Beverly Blvd, Los Angeles, CA 90048',
    bedrooms: 4,
    bathrooms: 3,
    max_guests: 8,
    amenities: ['pool', 'garden', 'wifi', 'kitchen', 'ac', 'parking'],
    property_type: 'Villa',
    latitude: 34.0722,
    longitude: -118.3784,
    average_rating: 4.9,
    review_count: 120,
    featured_until: null,
    created_at: '2023-06-20T10:00:00Z',
    slug: 'luxury-villa-pool',
  },
  {
    id: 'prop-004',
    owner_id: 'owner-4',
    title: 'Budget Hostel Dorm',
    description: 'Affordable shared dorm room with shared facilities',
    price_per_night: 25,
    status: 'available',
    city: 'Austin',
    country: 'USA',
    address: '321 Congress Ave, Austin, TX 78701',
    bedrooms: 0,
    bathrooms: 1,
    max_guests: 1,
    amenities: ['wifi', 'kitchen'],
    property_type: 'Room',
    latitude: 30.2672,
    longitude: -97.7431,
    average_rating: 3.8,
    review_count: 8,
    featured_until: null,
    created_at: '2024-01-01T10:00:00Z',
    slug: 'budget-hostel-dorm',
  },
  {
    id: 'prop-005',
    owner_id: 'owner-5',
    title: 'Family House with Backyard',
    description: 'Spacious family house perfect for vacations',
    price_per_night: 250,
    status: 'available',
    city: 'San Francisco',
    country: 'USA',
    address: '555 Golden Gate Ave, San Francisco, CA 94102',
    bedrooms: 3,
    bathrooms: 2,
    max_guests: 6,
    amenities: ['kitchen', 'parking', 'garden', 'wifi', 'washing_machine'],
    property_type: 'House',
    latitude: 37.7749,
    longitude: -122.4194,
    average_rating: 4.5,
    review_count: 67,
    featured_until: null,
    created_at: '2024-01-20T10:00:00Z',
    slug: 'family-house-backyard',
  },
  {
    id: 'prop-006',
    owner_id: 'owner-6',
    title: 'Modern Loft',
    description: 'Industrial-style loft with high ceilings',
    price_per_night: 200,
    status: 'available',
    city: 'Chicago',
    country: 'USA',
    address: '100 West Madison, Chicago, IL 60602',
    bedrooms: 2,
    bathrooms: 1.5,
    max_guests: 4,
    amenities: ['wifi', 'kitchen', 'ac', 'parking'],
    property_type: 'Loft',
    latitude: 41.8834,
    longitude: -87.6233,
    average_rating: 4.6,
    review_count: 34,
    featured_until: null,
    created_at: '2024-02-05T10:00:00Z',
    slug: 'modern-loft-chicago',
  },
  {
    id: 'prop-007',
    owner_id: 'owner-7',
    title: 'Cabin in Mountains',
    description: 'Rustic cabin with mountain views and fireplace',
    price_per_night: 120,
    status: 'available',
    city: 'Denver',
    country: 'USA',
    address: '2000 Peak Trail, Denver, CO 80202',
    bedrooms: 2,
    bathrooms: 1,
    max_guests: 4,
    amenities: ['fireplace', 'kitchen', 'wifi'],
    property_type: 'Cabin',
    latitude: 39.7392,
    longitude: -104.9903,
    average_rating: 4.7,
    review_count: 52,
    featured_until: null,
    created_at: '2023-12-10T10:00:00Z',
    slug: 'cabin-mountains',
  },
  {
    id: 'prop-008',
    owner_id: 'owner-8',
    title: 'Beach House with Terrace',
    description: 'Beautiful beachfront property with ocean views',
    price_per_night: 350,
    status: 'available',
    city: 'Miami',
    country: 'USA',
    address: '3000 Ocean Drive, Miami, FL 33139',
    bedrooms: 3,
    bathrooms: 2,
    max_guests: 6,
    amenities: ['wifi', 'kitchen', 'pool', 'parking', 'ac'],
    property_type: 'House',
    latitude: 25.7895,
    longitude: -80.13,
    average_rating: null,
    review_count: null,
    featured_until: null,
    created_at: '2024-02-28T10:00:00Z',
    slug: 'beach-house-terrace',
  },
  {
    id: 'prop-009',
    owner_id: 'owner-1',
    title: 'Penthouse with City View',
    description: 'Luxury penthouse with panoramic city views',
    price_per_night: 500,
    status: 'available',
    city: 'New York',
    country: 'USA',
    address: '1 Times Square, New York, NY 10036',
    bedrooms: 2,
    bathrooms: 2,
    max_guests: 4,
    amenities: ['wifi', 'kitchen', 'ac', 'parking', 'concierge'],
    property_type: 'Apartment',
    latitude: 40.758,
    longitude: -73.9855,
    average_rating: 4.9,
    review_count: 89,
    featured_until: null,
    created_at: '2023-09-15T10:00:00Z',
    slug: 'penthouse-city-view',
  },
  {
    id: 'prop-010',
    owner_id: 'owner-9',
    title: 'Countryside Cottage',
    description: 'Charming cottage in peaceful countryside',
    price_per_night: 95,
    status: 'available',
    city: 'Asheville',
    country: 'USA',
    address: '4000 Blue Ridge Parkway, Asheville, NC 28801',
    bedrooms: 2,
    bathrooms: 1,
    max_guests: 4,
    amenities: ['kitchen', 'fireplace', 'garden', 'wifi'],
    property_type: 'House',
    latitude: 35.5951,
    longitude: -82.5515,
    average_rating: 4.4,
    review_count: 23,
    featured_until: null,
    created_at: '2024-01-10T10:00:00Z',
    slug: 'countryside-cottage',
  },
  // Property with null coordinates (should fail geolocation validation)
  {
    id: 'prop-011',
    owner_id: 'owner-10',
    title: 'Vacant Property Without Coordinates',
    description: 'Property awaiting geolocation',
    price_per_night: 100,
    status: 'available',
    city: 'Seattle',
    country: 'USA',
    address: '5000 Pike Place, Seattle, WA 98101',
    bedrooms: 1,
    bathrooms: 1,
    max_guests: 2,
    amenities: ['wifi'],
    property_type: 'Studio',
    latitude: null,
    longitude: null,
    average_rating: null,
    review_count: null,
    featured_until: null,
    created_at: '2024-03-01T10:00:00Z',
    slug: 'vacant-property',
  },
];

// Test matrix: filter combinations with expected results
export const SEARCH_FILTER_TESTS = [
  {
    name: 'Empty query',
    filters: { query: '' },
    expectedIds: SEARCH_FIXTURES.map((p) => p.id),
  },
  {
    name: 'Text search: apartment',
    filters: { query: 'apartment' },
    expectedIds: ['prop-001', 'prop-009'],
  },
  {
    name: 'Text search: modern',
    filters: { query: 'modern' },
    expectedIds: ['prop-001', 'prop-006'],
  },
  {
    name: 'City filter: New York',
    filters: { city: 'New York' },
    expectedIds: ['prop-001', 'prop-009'],
  },
  {
    name: 'City filter: Los Angeles',
    filters: { city: 'Los Angeles' },
    expectedIds: ['prop-003'],
  },
  {
    name: 'Price range: 50-150',
    filters: { min_price: 50, max_price: 150 },
    expectedIds: ['prop-002', 'prop-004', 'prop-007', 'prop-010'],
  },
  {
    name: 'Price range: 300-500',
    filters: { min_price: 300, max_price: 500 },
    expectedIds: ['prop-003', 'prop-008', 'prop-009'],
  },
  {
    name: 'Bedrooms: 2+',
    filters: { bedrooms: 2 },
    expectedIds: ['prop-001', 'prop-005', 'prop-006', 'prop-007', 'prop-009', 'prop-010'],
  },
  {
    name: 'Bedrooms: 3+',
    filters: { bedrooms: 3 },
    expectedIds: ['prop-003', 'prop-005', 'prop-008'],
  },
  {
    name: 'Max guests: 4',
    filters: { guests: 4 },
    expectedIds: [
      'prop-001',
      'prop-003',
      'prop-005',
      'prop-006',
      'prop-007',
      'prop-009',
      'prop-010',
    ],
  },
  {
    name: 'Amenities: pool',
    filters: { amenities: ['pool'] },
    expectedIds: ['prop-003', 'prop-008'],
  },
  {
    name: 'Amenities: wifi, kitchen',
    filters: { amenities: ['wifi', 'kitchen'] },
    expectedIds: [
      'prop-001',
      'prop-002',
      'prop-003',
      'prop-004',
      'prop-005',
      'prop-006',
      'prop-007',
      'prop-009',
      'prop-010',
      'prop-011',
    ],
  },
  {
    name: 'Property type: House',
    filters: { property_types: ['House'] },
    expectedIds: ['prop-005', 'prop-008', 'prop-010'],
  },
  {
    name: 'Property types: Apartment, Villa',
    filters: { property_types: ['Apartment', 'Villa'] },
    expectedIds: ['prop-001', 'prop-003', 'prop-009'],
  },
  {
    name: 'Combined: New York + 2+ bedrooms + 150-200 price',
    filters: {
      city: 'New York',
      bedrooms: 2,
      min_price: 150,
      max_price: 200,
    },
    expectedIds: ['prop-001'],
  },
  {
    name: 'Combined: House type + 3+ bedrooms + pool',
    filters: {
      property_types: ['House'],
      bedrooms: 3,
      amenities: ['pool'],
    },
    expectedIds: ['prop-008'],
  },
  {
    name: 'Combined: 2 guests max + text search',
    filters: {
      guests: 2,
      query: 'studio',
    },
    expectedIds: ['prop-002'],
  },
];

// Sorting test cases
export const SEARCH_SORT_TESTS = [
  {
    name: 'Sort by price ascending',
    sortBy: 'price_asc',
    expectedOrder: ['prop-004', 'prop-002', 'prop-010', 'prop-007', 'prop-001', 'prop-006'],
  },
  {
    name: 'Sort by price descending',
    sortBy: 'price_desc',
    expectedOrder: ['prop-009', 'prop-003', 'prop-008', 'prop-005', 'prop-006', 'prop-001'],
  },
  {
    name: 'Sort by rating (highest first)',
    sortBy: 'rating',
    expectedOrder: ['prop-001', 'prop-009', 'prop-003', 'prop-007', 'prop-006', 'prop-005'],
  },
  {
    name: 'Sort by newest first',
    sortBy: 'newest',
    expectedOrder: ['prop-011', 'prop-008', 'prop-010', 'prop-005', 'prop-002', 'prop-006'],
  },
];

// Pagination test cases
export const SEARCH_PAGINATION_TESTS = [
  {
    name: 'Page 1, limit 5',
    page: 1,
    limit: 5,
    expectedCount: 5,
  },
  {
    name: 'Page 2, limit 5',
    page: 2,
    limit: 5,
    expectedCount: 5,
  },
  {
    name: 'Page 3, limit 5',
    page: 3,
    limit: 5,
    expectedCount: 1,
  },
  {
    name: 'Page 1, limit 20',
    page: 1,
    limit: 20,
    expectedCount: 11,
  },
];

// Distance calculation test cases (for nearby search)
export const DISTANCE_CALCULATION_TESTS = [
  {
    name: 'New York City area',
    lat: 40.7128,
    lng: -74.006,
    radiusKm: 50,
    expectedCount: 2, // prop-001, prop-009
  },
  {
    name: 'Los Angeles area',
    lat: 34.0722,
    lng: -118.3784,
    radiusKm: 100,
    expectedCount: 1, // prop-003
  },
  {
    name: 'Midwest center',
    lat: 39.5,
    lng: -98.0,
    radiusKm: 1000,
    expectedCount: 8, // Most properties within 1000km of central US
  },
];
