export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transform: {
    '^.+\\.tsx?$': ['ts-jest', {
      tsconfig: {
        target: 'ES2022',
        module: 'CommonJS',
        moduleResolution: 'node',
        strict: true,
        esModuleInterop: true,
        rootDir: '.',
        paths: {
          '@/*': ['./src/*'],
          '@/services/*': ['./src/services/*'],
          '@/controllers/*': ['./src/controllers/*'],
          '@/middleware/*': ['./src/middleware/*'],
          '@/blockchain/*': ['./src/blockchain/*'],
          '@/types/*': ['./src/types/*'],
        },
        types: ['jest', 'node'],
      },
    }],
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/index.ts',
    '!src/blockchain/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  moduleNameMapper: {
    '^@/services/(.*)\\.(js|ts)$': '<rootDir>/src/services/$1',
    '^@/controllers/(.*)\\.(js|ts)$': '<rootDir>/src/controllers/$1',
    '^@/middleware/(.*)\\.(js|ts)$': '<rootDir>/src/middleware/$1',
    '^@/blockchain/(.*)\\.(js|ts)$': '<rootDir>/src/blockchain/$1',
    '^@/types/(.*)\\.(js|ts)$': '<rootDir>/src/types/$1',
    '^@/(.*)\\.(js|ts)$': '<rootDir>/src/$1',
    '^@/services/(.*)$': '<rootDir>/src/services/$1',
    '^@/controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@/middleware/(.*)$': '<rootDir>/src/middleware/$1',
    '^@/blockchain/(.*)$': '<rootDir>/src/blockchain/$1',
    '^@/types/(.*)$': '<rootDir>/src/types/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
    '(.*)\\.js$': '$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 10000,
};
